In [1]:
import configparser
import os

import pandas as pd

In [ ]:
os.chdir('../')

In [2]:
dataset = 'all_noHypoHyper'

In [3]:
data = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
data.read('../data.ini')
data = data['DEFAULT']

In [4]:
dataMutations = pd.read_csv('../' + data[f'{dataset}___mutations'], sep='\t', comment='#', engine='python')
dataMutations_RAS = pd.read_csv('../' + data[f'{dataset}_RAS___mutations'], sep='\t', comment='#', engine='python')
dataMutations_nonRAS = pd.read_csv('../' + data[f'{dataset}_nonRAS___mutations'], sep='\t', comment='#', engine='python')

In [5]:
dataMutations.groupby('Hugo_Symbol').filter(lambda x: x['Protein_Length'].nunique() > 1)[['Hugo_Symbol', 'Transcript_ID', 'Gene_Length', 'Protein_Length']].drop_duplicates()
# there are equals symbol with different transcript lengths
# TODO: use Transcript_ID as symbol, correct solution?

       Hugo_Symbol    Transcript_ID  Gene_Length  Protein_Length
1953        ABLIM1  ENST00000277895       253891             778
1967        ABLIM1  ENST00000369252       253891             718
2992          ACPP  ENST00000336375        50932             386
2993          ACPP  ENST00000351273        50932             418
3167         ACSL6  ENST00000379264       205254             722
...            ...              ...          ...             ...
382635        ANK2  ENST00000503271       565632            1114
382680        ANO6  ENST00000425752       224418             929
387245         TEF  ENST00000406644        31994             273
388400      DAB2IP  ENST00000259371       218474            1132
388614      SAMD12  ENST00000409003       432537             161

[396 rows x 4 columns]

In [7]:
genesLengths = dataMutations[['Transcript_ID', 'Protein_Length', 'Hugo_Symbol']]
genesLengths = genesLengths.rename(columns={'Transcript_ID': 'symbol', 'Protein_Length': 'length', 'Hugo_Symbol': 'gene'})
genesLengths = genesLengths.drop_duplicates()

genesLengths_RAS = dataMutations_RAS[['Transcript_ID', 'Protein_Length', 'Hugo_Symbol']]
genesLengths_RAS = genesLengths_RAS.rename(columns={'Transcript_ID': 'symbol', 'Protein_Length': 'length', 'Hugo_Symbol': 'gene'})
genesLengths_RAS = genesLengths_RAS.drop_duplicates()

genesLengths_nonRAS = dataMutations_nonRAS[['Transcript_ID', 'Protein_Length', 'Hugo_Symbol']]
genesLengths_nonRAS = genesLengths_nonRAS.rename(columns={'Transcript_ID': 'symbol', 'Protein_Length': 'length', 'Hugo_Symbol': 'gene'})
genesLengths_nonRAS = genesLengths_nonRAS.drop_duplicates()

In [8]:
genesLengths

                 symbol  length           gene
0       ENST00000263100     495           A1BG
14      ENST00000373993     594           A1CF
25      ENST00000373995     594           A1CF
26      ENST00000318602    1474            A2M
53      ENST00000299698    1454          A2ML1
...                 ...     ...            ...
388243  ENST00000176195     121            SCT
388265  ENST00000531638     125  RP11-998D10.1
388400  ENST00000259371    1132         DAB2IP
388605  ENST00000522441     727         ANKRD6
388614  ENST00000409003     161         SAMD12

[19029 rows x 3 columns]

In [9]:
mutationPositions = dataMutations[['Transcript_ID', 'Protein_position', 'Hugo_Symbol']]
mutationPositions = mutationPositions.rename(columns={'Transcript_ID': 'symbol', 'Protein_position': 'position', 'Hugo_Symbol': 'gene'})

mutationPositions_RAS = dataMutations_RAS[['Transcript_ID', 'Protein_position', 'Hugo_Symbol']]
mutationPositions_RAS = mutationPositions_RAS.rename(columns={'Transcript_ID': 'symbol', 'Protein_position': 'position', 'Hugo_Symbol': 'gene'})

mutationPositions_nonRAS = dataMutations_nonRAS[['Transcript_ID', 'Protein_position', 'Hugo_Symbol']]
mutationPositions_nonRAS = mutationPositions_nonRAS.rename(columns={'Transcript_ID': 'symbol', 'Protein_position': 'position', 'Hugo_Symbol': 'gene'})

In [10]:
mutationPositions

                 symbol  position     gene
0       ENST00000263100     292.0     A1BG
1       ENST00000263100     291.0     A1BG
2       ENST00000263100     485.0     A1BG
3       ENST00000263100     245.0     A1BG
4       ENST00000263100     451.0     A1BG
...                 ...       ...      ...
388628  ENST00000370652     942.0   GPR112
388629  ENST00000451261     463.0  DCAF8L2
388630  ENST00000378981     281.0   MAGEB1
388631  ENST00000357033    1741.0      DMD
388632  ENST00000496529     278.0  CCDC120

[388633 rows x 3 columns]

In [11]:
genesLengths.to_csv('../' + data['mutclustsw___all_noHypoHyper___in_dir'] + 'genesLengths.txt', sep='\t', index=False)
genesLengths_RAS.to_csv('../' + data['mutclustsw___all_noHypoHyper_RAS___in_dir'] + 'genesLengths.txt', sep='\t', index=False)
genesLengths_nonRAS.to_csv('../' + data['mutclustsw___all_noHypoHyper_nonRAS___in_dir'] + 'genesLengths.txt', sep='\t', index=False)

In [12]:
mutationPositions.to_csv('../' + data['mutclustsw___all_noHypoHyper___in_dir'] + 'mutationPositions.txt', sep='\t', index=False)
mutationPositions_RAS.to_csv('../' + data['mutclustsw___all_noHypoHyper_RAS___in_dir'] + 'mutationPositions.txt', sep='\t', index=False)
mutationPositions_nonRAS.to_csv('../' + data['mutclustsw___all_noHypoHyper_nonRAS___in_dir'] + 'mutationPositions.txt', sep='\t', index=False)