In [1]:
import configparser
import os

import pandas as pd

In [ ]:
os.chdir('../')

In [2]:
dataset = 'all_noHypoHyper'

In [3]:
data = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
data.read('../data.ini')
data = data['DEFAULT']

### all

In [4]:
dataSamples = pd.read_csv('../' + data[f'{dataset}___samples'], sep='\t', comment='#', engine='python')
dataSamples = pd.DataFrame({'ID': range(0, dataSamples['SAMPLE_ID'].nunique()), 'Sample' : dataSamples['SAMPLE_ID'].unique(), 'Cohort': ['colorectal']*dataSamples['SAMPLE_ID'].nunique()})
dataSamples

        ID                     Sample      Cohort
0        0  coadread_dfci_2016_207430  colorectal
1        1    coadread_dfci_2016_1241  colorectal
2        2    coadread_dfci_2016_3701  colorectal
3        3    coadread_dfci_2016_3640  colorectal
4        4    coadread_dfci_2016_1222  colorectal
...    ...                        ...         ...
1114  1114            TCGA-RU-A8FL-01  colorectal
1115  1115            TCGA-SS-A7HO-01  colorectal
1116  1116            TCGA-T9-A92H-01  colorectal
1117  1117            TCGA-5M-AAT5-01  colorectal
1118  1118            TCGA-5M-AATA-01  colorectal

[1119 rows x 3 columns]

In [5]:
dataSamples.to_csv('../' + data[f'mutpanning___{dataset}___in_dir'] + '/samples.txt', sep='\t', index=False)

In [6]:
dataMutations = pd.read_csv('../' + data[f'{dataset}___mutations'], sep='\t', comment='#', engine='python')
dataMutations

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100,8322,1,495
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100,8322,1,495
2,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100,8322,1,495
3,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100,8322,1,495
4,coadread_dfci_2016_2624,A1BG,A1BG,19,58858848,58858848,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.1351G>A,p.A451T,451.0,ENST00000263100,8322,1,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388628,TCGA-T9-A92H-01,GPR112,GPR112,X,135428691,135428691,+,Silent,SNP,T,T,G,ENST00000370652.1:c.2826T>G,p.T942=,942.0,ENST00000370652,136094,1,3080
388629,TCGA-T9-A92H-01,DCAF8L2,DCAF8L2,X,27766401,27766401,+,Silent,SNP,T,T,C,ENST00000451261.2:c.1389T>C,p.F463=,463.0,ENST00000451261,158410,1,631
388630,TCGA-T9-A92H-01,MAGEB1,MAGEB1,X,30269452,30269452,+,Missense_Mutation,SNP,C,C,G,ENST00000378981.3:c.842C>G,p.T281S,281.0,ENST00000378981,8309,1,347
388631,TCGA-T9-A92H-01,DMD,DMD,X,32381009,32381009,+,Missense_Mutation,SNP,A,A,C,ENST00000357033.4:c.5221T>G,p.L1741V,1741.0,ENST00000357033,2241765,1,3685
388632,TCGA-T9-A92H-01,CCDC120,CCDC120,X,48923135,48923135,+,Missense_Mutation,SNP,G,G,A,ENST00000496529.2:c.833G>A,p.R278Q,278.0,ENST00000496529,16409,1,630

In [7]:
dataMutations.to_csv('../' + data[f'mutpanning___{dataset}___in_dir'] + '/mutations.maf', sep='\t', index=False)

### RAS and nonRAS

In [8]:
dataSamples_RAS = pd.read_csv('../' + data[f'{dataset}_RAS___samples'], sep='\t', comment='#', engine='python')
dataSamples_RAS = pd.DataFrame({'ID': range(0, dataSamples_RAS['SAMPLE_ID'].nunique()), 'Sample' : dataSamples_RAS['SAMPLE_ID'].unique(), 'Cohort': ['colorectal']*dataSamples_RAS['SAMPLE_ID'].nunique()})

dataSamples_nonRAS = pd.read_csv('../' + data[f'{dataset}_nonRAS___samples'], sep='\t', comment='#', engine='python')
dataSamples_nonRAS = pd.DataFrame({'ID': range(0, dataSamples_nonRAS['SAMPLE_ID'].nunique()), 'Sample' : dataSamples_nonRAS['SAMPLE_ID'].unique(), 'Cohort': ['colorectal']*dataSamples_nonRAS['SAMPLE_ID'].nunique()})

In [9]:
dataSamples_RAS.to_csv('../' + data[f'mutpanning___{dataset}_RAS___in_dir'] + '/samples.txt', sep='\t', index=False)

dataSamples_nonRAS.to_csv('../' + data[f'mutpanning___{dataset}_nonRAS___in_dir'] + '/samples.txt', sep='\t', index=False)

In [10]:
dataMutations_RAS = pd.read_csv('../' + data[f'{dataset}_RAS___mutations'], sep='\t', comment='#', engine='python')

dataMutations_nonRAS = pd.read_csv('../' + data[f'{dataset}_nonRAS___mutations'], sep='\t', comment='#', engine='python')

In [11]:
dataMutations_RAS.to_csv('../' + data[f'mutpanning___{dataset}_RAS___in_dir'] + '/mutations.maf', sep='\t', index=False)

dataMutations_nonRAS.to_csv('../' + data[f'mutpanning___{dataset}_nonRAS___in_dir'] + '/mutations.maf', sep='\t', index=False)