In [1]:
import configparser
import os

import pandas as pd

In [ ]:
os.chdir('../')

In [2]:
dataset = 'all_noHypoHyper'

In [3]:
data = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
data.read('../data.ini')
data = data['DEFAULT']

In [4]:
mutsig = pd.read_csv("../" + data[f'mutsig___{dataset}___out_dir'] + '/sig_genes.txt', sep='\t', engine='python', comment='#')
mutsig_RAS = pd.read_csv("../" + data[f'mutsig___{dataset}_RAS___out_dir'] + '/sig_genes.txt', sep='\t', engine='python', comment='#')
mutsig_nonRAS = pd.read_csv("../" + data[f'mutsig___{dataset}_nonRAS___out_dir'] + '/sig_genes.txt', sep='\t', engine='python', comment='#')

In [5]:
mutsig

,rank,gene,longname,codelen,nnei,nncd,nsil,nmis,nstp,nspl,nind,nnon,npat,nsite,pCV,pCL,pFN,p,q
0,1,APC,adenomatous polyposis coli,8592,7,0,13,80,641,0,334,1055,733,449,1.000000e-16,0.00001,1.00000,1.000000e-16,1.450923e-13
1,2,TP53,tumor protein p53,1314,2,0,3,504,79,5,76,664,628,204,4.588351e-16,0.00001,0.00001,1.000000e-16,1.450923e-13
2,3,FBXW7,F-box and WD repeat domain containing 7,2580,6,0,4,126,46,0,23,195,167,99,6.283482e-15,0.00001,0.00001,1.000000e-16,1.450923e-13
3,4,SMAD4,SMAD family member 4,1699,11,0,4,118,19,1,15,153,138,98,4.116163e-15,0.00001,0.00052,1.000000e-16,1.450923e-13
4,5,FAM123B,family with sequence similarity 123B,3412,20,0,6,24,60,0,22,106,104,59,3.007129e-15,0.00002,0.98310,1.000000e-16,1.450923e-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18857,18858,AGAP8,"ArfGAP with GTPase domain, ankyrin repeat and ...",2016,73,0,1,0,0,0,0,0,0,0,1.000000e+00,NaN,NaN,1.000000e+00,1.000000e+00
18858,18859,AGAP11,ankyrin repeat and GTPase domain Arf GTPase ac...,1669,1,0,0,0,0,0,0,0,0,0,1.000000e+00,NaN,NaN,1.000000e+00,1.000000e+00
18859,18860,AG2,anterior gradient 2 homolog (Xenopus laevis),369,0,0,2,0,0,0,0,0,0,0,1.000000e+00,NaN,NaN,1.000000e+00,1.000000e+00
18860,18861,ABO,"ABO blood group (transferase A, alpha 1-3-N-ac...",1090,0,0,0,0,0,0,0,0,0,0,1.000000e+00,NaN,NaN,1.000000e+00,1.000000e+00
18861,18862,A2LD1,NaN,466,0,0,1,0,0,0,0,0,0,0,1.000000e+00,NaN,NaN,1.000000e+00,1.000000e+00

In [6]:
mutsig = mutsig[['gene','longname', 'p', 'q']].rename(columns={'gene':'#gene'})
mutsig_RAS = mutsig_RAS[['gene','longname', 'p', 'q']].rename(columns={'gene':'#gene'})
mutsig_nonRAS = mutsig_nonRAS[['gene','longname', 'p', 'q']].rename(columns={'gene':'#gene'})

In [7]:
mutsig

,#gene,longname,p,q
0,APC,adenomatous polyposis coli,1.000000e-16,1.450923e-13
1,TP53,tumor protein p53,1.000000e-16,1.450923e-13
2,FBXW7,F-box and WD repeat domain containing 7,1.000000e-16,1.450923e-13
3,SMAD4,SMAD family member 4,1.000000e-16,1.450923e-13
4,FAM123B,family with sequence similarity 123B,1.000000e-16,1.450923e-13
...,...,...,...,...
18857,AGAP8,"ArfGAP with GTPase domain, ankyrin repeat and ...",1.000000e+00,1.000000e+00
18858,AGAP11,ankyrin repeat and GTPase domain Arf GTPase ac...,1.000000e+00,1.000000e+00
18859,AG2,anterior gradient 2 homolog (Xenopus laevis),1.000000e+00,1.000000e+00
18860,ABO,"ABO blood group (transferase A, alpha 1-3-N-ac...",1.000000e+00,1.000000e+00
18861,A2LD1,NaN,1.000000e+00,1.000000e+00

In [8]:
mutsig.to_csv("../" + data[f'netsig___{dataset}___in'], sep='\t', index=False)
mutsig_RAS.to_csv("../" + data[f'netsig___{dataset}_RAS___in'], sep='\t', index=False)
mutsig_nonRAS.to_csv("../" + data[f'netsig___{dataset}_nonRAS___in'], sep='\t', index=False)