In [1]:
import pandas as pd

In [2]:
from machine_learning.testMl import testMl

In [3]:
testMl(
    [
        # merged dataset - mut (accuracy optimised)
        'merged_mut',
        'merged_mut_["mutclust - ALL"]',
        'merged_mut_["oncodriveclustl_coadreadParams - ALL"]',
        'merged_mut_["oncodriveclustl_defaultParams - ALL"]',
        'merged_mut_["onlyMutclust - ALL"]',
        'merged_mut_["onlyOncodriveclustl_coadreadParams - ALL"]',
        'merged_mut_["onlyOncodriveclustl_defaultParams - ALL"]',
    ],
    'accuracy',
    'merged_mut.csv'
)

In [4]:
testMl(
    [
        # merged dataset - mut (mcc optimised)
        'merged_mut',
        'merged_mut_["mutclust - ALL"]',
        'merged_mut_["oncodriveclustl_coadreadParams - ALL"]',
        'merged_mut_["oncodriveclustl_defaultParams - ALL"]',
        'merged_mut_["onlyMutclust - ALL"]',
        'merged_mut_["onlyOncodriveclustl_coadreadParams - ALL"]',
        'merged_mut_["onlyOncodriveclustl_defaultParams - ALL"]',
    ],
    'mcc',
    'merged_mut_mcc.csv'
)

In [5]:
accuracy = pd.read_csv('../data/ml/results/merged_mut.csv', sep='\t', index_col=0)
mcc = pd.read_csv('../data/ml/results/merged_mut_mcc.csv', sep='\t', index_col=0)

In [6]:
accuracy.sort_values('MCC', ascending=False)

,dataset,data,model,genes tool,genes tool set,isTranFiltered,clusters tool,cluster tool set,#features,#nonZeroParams_lasso,...,f1 nonRAS,f1 RAS,MCC,#train sample,#test sample,%train sample,%test sample,#iterations,best params,grid optimized
82,merged,mut,linearSVM,maxmif HN S,onlyRAS_onlyNonRAS,NaN,NaN,NaN,3977,NaN,...,0.729114,0.613718,0.343843,783,336,100.000000,100.000000,1882.0,{'C': 0.001584893192461114},accuracy
1151,merged,mut,logisticRegressionLasso,muffinn maxHN,onlyRAS,NaN,onlyMutclust,ALL,27,1.0,...,0.756757,0.550000,0.337126,105,57,13.409962,16.964286,3.0,{'C': 0.1},accuracy
337,merged,mut,linearSVM,maxmif HN S,onlyRAS_onlyNonRAS,NaN,mutclust,ALL,4431,NaN,...,0.719794,0.614841,0.334746,783,336,100.000000,100.000000,1897.0,{'C': 0.001995262314968879},accuracy
83,merged,mut,polynomialSVM,maxmif HN S,onlyRAS_onlyNonRAS,NaN,NaN,NaN,3977,NaN,...,0.746479,0.560976,0.328526,783,336,100.000000,100.000000,1139.0,"{'C': 1.0, 'coef0': 1.0, 'degree': 2}",accuracy
335,merged,mut,logisticRegression,maxmif HN S,onlyRAS_onlyNonRAS,NaN,mutclust,ALL,4431,NaN,...,0.692098,0.629508,0.325901,783,336,100.000000,100.000000,8.0,{},accuracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,merged,mut,randomForest,mutsig,onlyRAS,NaN,onlyMutclust,ALL,56,NaN,...,0.416667,0.382353,-0.200980,173,70,22.094508,20.833333,NaN,"{'max_features': 'log2', 'min_samples_split': ...",accuracy
1065,merged,mut,logisticRegression,hotnet2,ALL,NaN,onlyMutclust,ALL,73,NaN,...,0.535714,0.235294,-0.225467,245,90,31.289911,26.785714,9.0,{},accuracy
1449,merged,mut,randomForest,muffinn maxS,onlyRAS,NaN,onlyOncodriveclustl_coadreadParams,ALL,89,NaN,...,0.574074,0.178571,-0.230287,212,82,27.075351,24.404762,NaN,"{'max_features': 'sqrt', 'min_samples_split': ...",accuracy
1112,merged,mut,linearSVM,maxmif HN S,onlyRAS,NaN,onlyMutclust,ALL,88,NaN,...,0.666667,0.000000,-0.231662,241,92,30.779055,27.380952,205.0,{'C': 0.003981071705534973},accuracy
1445,merged,mut,logisticRegression,muffinn maxS,onlyRAS,NaN,onlyOncodriveclustl_coadreadParams,ALL,89,NaN,...,0.489796,0.242424,-0.267340,212,82,27.075351,24.404762,8.0,{},accuracy

In [7]:
mcc.sort_values('MCC', ascending=False)

,dataset,data,model,genes tool,genes tool set,isTranFiltered,clusters tool,cluster tool set,#features,#nonZeroParams_lasso,...,f1 nonRAS,f1 RAS,MCC,#train sample,#test sample,%train sample,%test sample,#iterations,best params,grid optimized
1796,merged,mut,logisticRegressionLasso,mutsig,RAS,NaN,onlyOncodriveclustl_defaultParams,ALL,202,8.0,...,0.437158,0.694362,0.349829,631,260,80.587484,77.380952,5.0,{'C': 0.039810717055349734},mcc
1151,merged,mut,logisticRegressionLasso,muffinn maxHN,onlyRAS,NaN,onlyMutclust,ALL,27,1.0,...,0.756757,0.550000,0.337126,105,57,13.409962,16.964286,3.0,{'C': 0.1},mcc
337,merged,mut,linearSVM,maxmif HN S,onlyRAS_onlyNonRAS,NaN,mutclust,ALL,4431,NaN,...,0.719794,0.614841,0.334746,783,336,100.000000,100.000000,1897.0,{'C': 0.001995262314968879},mcc
76,merged,mut,logisticRegressionLasso,maxmif HN S,onlyRAS_onlyNonRAS,NaN,NaN,NaN,3977,3947.0,...,0.704000,0.626263,0.331719,783,336,100.000000,100.000000,10.0,{'C': 50118.72336272725},mcc
1536,merged,mut,logisticRegressionLasso,mutsig,RAS,NaN,onlyOncodriveclustl_coadreadParams,ALL,232,9.0,...,0.414508,0.674352,0.328175,665,270,84.929757,80.357143,5.0,{'C': 0.039810717055349734},mcc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,merged,mut,logisticRegression,hotnet2,ALL,NaN,onlyMutclust,ALL,73,NaN,...,0.535714,0.235294,-0.225467,245,90,31.289911,26.785714,9.0,{},mcc
1449,merged,mut,randomForest,muffinn maxS,onlyRAS,NaN,onlyOncodriveclustl_coadreadParams,ALL,89,NaN,...,0.574074,0.178571,-0.230287,212,82,27.075351,24.404762,NaN,"{'max_features': 'sqrt', 'min_samples_split': ...",mcc
1353,merged,mut,polynomialSVM,maxmif HN,onlyRAS,NaN,onlyOncodriveclustl_coadreadParams,ALL,77,NaN,...,0.384615,0.384615,-0.230769,159,52,20.306513,15.476190,4593109.0,"{'C': 10000.0, 'coef0': 100.0, 'degree': 5}",mcc
1448,merged,mut,polynomialSVM,muffinn maxS,onlyRAS,NaN,onlyOncodriveclustl_coadreadParams,ALL,89,NaN,...,0.552381,0.203390,-0.234755,212,82,27.075351,24.404762,488.0,"{'C': 100000.0, 'coef0': 0.01, 'degree': 3}",mcc
1445,merged,mut,logisticRegression,muffinn maxS,onlyRAS,NaN,onlyOncodriveclustl_coadreadParams,ALL,89,NaN,...,0.489796,0.242424,-0.267340,212,82,27.075351,24.404762,8.0,{},mcc